# Generated by Django 3.2.7 on 2021-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capitals',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=255, primary_key=True, serialize=False)),
                ('population', models.CharField(db_column='Population', max_length=255)),
                ('area', models.CharField(db_column='Area', max_length=255)),
                ('governor', models.CharField(db_column='Governor', max_length=255)),
                ('coordinates', models.CharField(db_column='Coordinates', max_length=500)),
            ],
            options={
                'db_table': 'capitals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=255, primary_key=True, serialize=False)),
                ('official_languages', models.CharField(blank=True, db_column='Official_languages', max_length=300, null=True)),
                ('population', models.CharField(db_column='Population', max_length=255)),
                ('driving_side', models.CharField(db_column='Driving_side', max_length=255)),
                ('calling_code', models.CharField(db_column='Calling_code', max_length=255)),
                ('time_zone', models.CharField(db_column='Time_zone', max_length=255)),
                ('continent', models.CharField(db_column='Continent', max_length=255)),
                ('capital_area', models.CharField(db_column='Capital_Area', max_length=255)),
                ('area', models.CharField(blank=True, db_column='Area', max_length=255, null=True)),
                ('water', models.CharField(db_column='Water', max_length=255)),
                ('legislature', models.CharField(blank=True, db_column='Legislature', max_length=1000, null=True)),
                ('ruler', models.CharField(db_column='Ruler', max_length=255)),
                ('hdi', models.CharField(db_column='HDI', max_length=255)),
                ('currency', models.CharField(db_column='Currency', max_length=255)),
                ('gdp_total', models.CharField(db_column='GDP_Total', max_length=255)),
                ('gdp_per_capita', models.CharField(db_column='GDP_Per_Capita', max_length=255)),
                ('gini', models.CharField(db_column='Gini', max_length=255)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RulersAll',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=255, primary_key=True, serialize=False)),
                ('birth_date', models.CharField(db_column='Birth_Date', max_length=255)),
                ('assumed_office', models.CharField(db_column='Assumed_Office', max_length=255)),
                ('political_party', models.CharField(db_column='Political_Party', max_length=255)),
                ('country', models.CharField(db_column='Country', max_length=255)),
            ],
            options={
                'db_table': 'rulers_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
